name: inventory-service

image:
  repository: cityonkar/inventory-service
  tag: "1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
