name: order-service

image:
  repository: cityonkar/order-service
  tag: "7"

env:
  DB_HOST: order-service-db.cepumyous0um.us-east-1.rds.amazonaws.com
  DB_PORT: "3306"

secrets:
  enabled: true
  name: order-db-secret
