name: payment-service

image:
  repository: cityonkar/payment-service
  tag: "git-6225dfb"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  path: /payments

serviceMonitor:
  enabled: true

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
