replicaCount: 1

image:
  repository: cityonkar/user-service
  tag: "build-18"   # or git-sha / build number
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: jdbc:mysql://user-service-db.cepumyous0um.us-east-1.rds.amazonaws.com:3306/userdb


secrets:
  enabled: true
  name: user-db-secret

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
