grafana:
  enabled: true
  adminUser: admin

  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
    path: /grafana
    pathType: Prefix

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
