apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/CityOnkar/java-microservices-devsecops.git
    targetRevision: HEAD
    path: helm/microservice
    helm:
      valueFiles:
        - values/inventory-service.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: inventory-service

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
